# Generated by Django 6.0 on 2025-12-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalshop', '0003_medicine_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalshop',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude for GIS location', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='medicalshop',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude for GIS location', max_digits=9, null=True),
        ),
    ]
