# Generated by Django 6.0 on 2025-12-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('doctor', 'Doctor'), ('user', 'User'), ('medicalshop', 'Medical Shop')], max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-login_time'],
            },
        ),
    ]
